/*
 * ESP32-S3 Dual 1.28" Round Display (GC9A01)
 * WLE5 Animation Engine - Real-Time Kinematics & FFat Dynamic Configuration
 */

#include <TFT_eSPI.h>
#include <SPI.h>
#include <ESP32Servo.h>
#include <Adafruit_PWMServoDriver.h> 
#include "FS.h"
#include "SD_MMC.h"
#include <Wire.h>
#include <FFat.h> // Internal Flash File System

// Auto-generated by Python IDE (Virtual Joints Only)
#include "robot_config.h"

// --- AUDIO DRIVERS ---
#include "src/I2C_Driver.h"
#include "src/I2S_Driver.h"
#include "src/Audio_ES8311.h"

extern "C" {
  #include "src/es8311.h"
}
#include "Audio.h"

// --- HARDWARE PIN DEFINITIONS ---
#define TFT_SCLK 41
#define TFT_MOSI 42
#define TFT_DC   45
#define TFT_CS1  47
#define TFT_RST1 48
#define TFT_BL1  46
#define TFT_CS2  38
#define TFT_RST2 8
#define TFT_BL2  39

#define I2S_MCLK 12 
#define I2S_BCLK 13 
#define I2S_LRC  14 
#define I2S_DOUT 15 

#define AUX_I2C_SDA 4
#define AUX_I2C_SCL 5
#define ACK_BYTE 0x01

// ==========================================
// BINARY FILE STRUCTURES (Matches Python exact byte packing)
// ==========================================
struct __attribute__((packed)) BinJointConfig {
    uint8_t id;
    char name[32];
    uint8_t region;
    uint8_t control_type;
    int8_t hardware_address;
    float r_min;
    float r_max;
    float r_init;
    int16_t cmd_min;
    int16_t cmd_max;
    int16_t cmd_init; // <-- CHANGED from uint8_t
    uint8_t def_spd;
    uint8_t max_spd;
    uint8_t max_acc;
};

struct __attribute__((packed)) BinCommand {
    uint8_t joint_id;
    uint8_t setpoint;
    uint8_t speed;
};

struct BinKeyframe {
    uint8_t time_tenths; 
    uint8_t cmd_count;
    BinCommand commands[16]; 
};

struct BinAnimation {
    char name[32];
    uint16_t kf_count;
    BinKeyframe* keyframes; 
};

struct EngineState {
    int32_t current_position;
    int32_t target_position;
    int32_t current_velocity;
    int32_t target_velocity;
};

// --- GLOBAL ENGINE STATES ---
BinJointConfig ROBOT_CONFIG[256]; 
bool joint_is_active[256] = {false}; 
EngineState engine_states[256];
bool isAsymmetric = false;

File uploadFile;
BinAnimation* activeAnimations = nullptr;
uint8_t activeAnimationCount = 0;

// Playback Controls
uint8_t active_anim_id = 0;        
uint16_t current_frame_idx = 0;
unsigned long anim_start_time = 0;

// Hardware Drivers
TFT_eSPI tft = TFT_eSPI(); 
TFT_eSprite img = TFT_eSprite(&tft); 
Servo physical_servos[6]; 
Adafruit_PWMServoDriver pca9685 = Adafruit_PWMServoDriver(0x40, Wire1); 

Audio audio;
TaskHandle_t AudioTask;
uint32_t current_sample_rate = 0;

#define MAX_ASSETS 20
uint16_t* cachedImages[MAX_ASSETS] = {nullptr};
String audioPaths[MAX_ASSETS] = {""};
volatile int requestedAudioIndex = -1;

const int WIDTH = 234; const int HEIGHT = 234;
const int CENTER_X = 117; const int CENTER_Y = 117; const int OFFSET = 3; 

uint8_t dist_map[120][120];
uint8_t bezel_mask[120][120]; 

unsigned long lastPhysicsTick = 0;
unsigned long lastFrameTime = 0;
int currentFPS = 0;

// --- FORWARD DECLARATIONS (CRITICAL FOR COMPILER) ---
void renderEyeFrame(float t, bool isRightEye);
void updateJointPhysics(uint8_t joint_id); 

// --- FFAT BINARY PARSERS ---
void loadHardwareConfig() {
    for (int i = 0; i < 256; i++) joint_is_active[i] = false;
    
    if (!FFat.exists("/config.bin")) {
        Serial.println("No config.bin found on FFat.");
        return;
    }

    File f = FFat.open("/config.bin", "r");
    if (!f) return;

    char header[4];
    f.readBytes(header, 4);
    if (strncmp(header, "WLEC", 4) != 0) {
        Serial.println("Invalid config.bin header!");
        f.close(); return;
    }

    uint32_t version;
    f.readBytes((char*)&version, 4);
    
    uint8_t count;
    f.readBytes((char*)&count, 1);
    Serial.printf("Loading Config v%d (%d joints)...\n", version, count);

    for (uint8_t i = 0; i < count; i++) {
        BinJointConfig temp;
        f.readBytes((char*)&temp, sizeof(BinJointConfig));
        
        ROBOT_CONFIG[temp.id] = temp;
        joint_is_active[temp.id] = true;

// CHANGED: No more math needed! It just reads the raw 1500 value safely.
        int16_t mapped_default = temp.cmd_init;
                
        engine_states[temp.id].current_position = mapped_default;
        engine_states[temp.id].target_position = mapped_default;
        engine_states[temp.id].current_velocity = 0;
        engine_states[temp.id].target_velocity = temp.def_spd;
    }
    f.close();
}

void loadAnimations() {
    if (!FFat.exists("/anims.bin")) {
        Serial.println("No anims.bin found on FFat.");
        return;
    }

    File f = FFat.open("/anims.bin", "r");
    if (!f) return;

    char header[4];
    f.readBytes(header, 4);
    if (strncmp(header, "WLEA", 4) != 0) {
        Serial.println("Invalid anims.bin header!");
        f.close(); return;
    }

    uint32_t hash;
    f.readBytes((char*)&hash, 4);
    
    f.readBytes((char*)&activeAnimationCount, 1);
    Serial.printf("Loading %d Animations (Hash: %u)...\n", activeAnimationCount, hash);

    if (activeAnimations != nullptr) {
        for (uint8_t i = 0; i < activeAnimationCount; i++) delete[] activeAnimations[i].keyframes;
        delete[] activeAnimations;
    }

    activeAnimations = new BinAnimation[activeAnimationCount];

    for (uint8_t i = 0; i < activeAnimationCount; i++) {
        f.readBytes(activeAnimations[i].name, 32);
        f.readBytes((char*)&activeAnimations[i].kf_count, 2);
        
        activeAnimations[i].keyframes = new BinKeyframe[activeAnimations[i].kf_count];
        
        for (uint16_t k = 0; k < activeAnimations[i].kf_count; k++) {
            f.readBytes((char*)&activeAnimations[i].keyframes[k].time_tenths, 1);
            f.readBytes((char*)&activeAnimations[i].keyframes[k].cmd_count, 1);
            
            for (uint8_t c = 0; c < activeAnimations[i].keyframes[k].cmd_count; c++) {
                f.readBytes((char*)&activeAnimations[i].keyframes[k].commands[c], sizeof(BinCommand));
            }
        }
    }
    f.close();
}

// --- UNIFIED AUDIO & VOLUME CONTROL ---
void setMasterVolume(uint8_t vol_0_100) {
  if (vol_0_100 > 100) vol_0_100 = 100;
  Volume_adjustment(vol_0_100); 
  uint8_t sw_vol = map(vol_0_100, 0, 100, 0, 21);
  audio.setVolume(sw_vol);
}

void loadAllAssets() {
  fs::File imgDir = SD_MMC.open("/img");
  if (imgDir) {
    fs::File file = imgDir.openNextFile();
    while (file) {
      String fname = file.name();
      int slashIdx = fname.lastIndexOf('/');
      if (slashIdx >= 0) fname = fname.substring(slashIdx + 1);
      int idx = fname.toInt(); 
      if (idx >= 0 && idx < MAX_ASSETS && cachedImages[idx] == nullptr) {
        size_t sz = file.size();
        void* psramBuf = heap_caps_malloc(sz, MALLOC_CAP_SPIRAM);
        if (psramBuf) {
          file.read((uint8_t*)psramBuf, sz);
          cachedImages[idx] = (uint16_t*)psramBuf;
        }
      }
      file.close(); file = imgDir.openNextFile();
    }
  }

  fs::File audioDir = SD_MMC.open("/audio");
  if (audioDir) {
    fs::File file = audioDir.openNextFile();
    while (file) {
      String fname = file.name();
      int slashIdx = fname.lastIndexOf('/');
      if (slashIdx >= 0) fname = fname.substring(slashIdx + 1);
      int idx = fname.toInt();
      if (idx >= 0 && idx < MAX_ASSETS) audioPaths[idx] = file.path();
      file.close(); file = audioDir.openNextFile();
    }
  }
}

void audioTaskCode(void * parameter) {
  for(;;) {
    if (requestedAudioIndex > 0 && requestedAudioIndex < MAX_ASSETS) {
      if (audioPaths[requestedAudioIndex] != "") audio.connecttoFS(SD_MMC, audioPaths[requestedAudioIndex].c_str());
      requestedAudioIndex = -1; 
    } else if (requestedAudioIndex == 255) {
      audio.stopSong();
      requestedAudioIndex = -1;
    }
    audio.loop(); 

    uint32_t rate = audio.getSampleRate();
    if (rate > 0 && rate != current_sample_rate) {
      current_sample_rate = rate;
      es8311_handle_t temp_handle = es8311_create((i2c_port_t)0, ES8311_ADDRRES_0);
      es8311_sample_frequency_config(temp_handle, rate * 256, rate);
      es8311_delete(temp_handle);
    }
    
    vTaskDelay(1); 
  }
}

// --- SETUP ROUTINE ---
void setup() {
  Serial.begin(115200);
  Serial.setTimeout(50); 
  
  if (!FFat.begin(true)) Serial.println("Error: FFat Mount Failed!");
  
  loadHardwareConfig();
  loadAnimations();
  
  Wire1.begin(AUX_I2C_SDA, AUX_I2C_SCL);
  pca9685.begin();
  pca9685.setPWMFreq(50); 
  
  pinMode(TFT_CS1, OUTPUT); pinMode(TFT_CS2, OUTPUT);
  pinMode(TFT_RST1, OUTPUT); pinMode(TFT_RST2, OUTPUT);
  pinMode(TFT_BL1, OUTPUT); pinMode(TFT_BL2, OUTPUT);

  digitalWrite(TFT_BL1, LOW); digitalWrite(TFT_BL2, LOW);
  digitalWrite(TFT_RST1, LOW); digitalWrite(TFT_RST2, LOW);
  delay(50);
  digitalWrite(TFT_RST1, HIGH); digitalWrite(TFT_RST2, HIGH);
  delay(120);

  digitalWrite(TFT_CS1, LOW); digitalWrite(TFT_CS2, LOW);
  tft.init();
  digitalWrite(TFT_CS1, HIGH); digitalWrite(TFT_CS2, HIGH);
  digitalWrite(TFT_CS1, LOW); tft.setRotation(1); digitalWrite(TFT_CS1, HIGH);
  digitalWrite(TFT_CS2, LOW); tft.setRotation(3); digitalWrite(TFT_CS2, HIGH);
  
  digitalWrite(TFT_CS1, LOW); digitalWrite(TFT_CS2, LOW); 
  tft.fillScreen(tft.color565(25, 25, 30)); 
  digitalWrite(TFT_CS1, HIGH); digitalWrite(TFT_CS2, HIGH);

  img.setColorDepth(16);
  img.createSprite(WIDTH, HEIGHT);

  for(int y=0; y<120; y++) {
    for(int x=0; x<120; x++) {
      float d = sqrt(x*x + y*y);
      dist_map[y][x] = (uint8_t)min(255.0f, d);
      if (d < 104.0) bezel_mask[y][x] = 0;   
      else if (d >= 105.5) bezel_mask[y][x] = 255; 
      else bezel_mask[y][x] = (uint8_t)((d - 104.0) * 170.0); 
    }
  }

  SD_MMC.setPins(17, 21, 18); 
  if (SD_MMC.begin("/sdcard", true)) {
    loadAllAssets();
  }

  I2C_Init(); I2S_Init(24000); Audio_Init(24000); 
  setMasterVolume(80); 
  Audio_PA_EN();

  i2s.end();
  audio.setPinout(I2S_BCLK, I2S_LRC, I2S_DOUT, I2S_MCLK);
  xTaskCreatePinnedToCore(audioTaskCode, "AudioTask", 8192, NULL, 2, &AudioTask, 0);

  digitalWrite(TFT_BL1, HIGH); digitalWrite(TFT_BL2, HIGH);
}

// --- COMMAND INGESTION ---
void pushCommandToEngine(uint8_t id, uint8_t setpoint, uint8_t speed) {
    if (id == V_AUDIO_PLAY) { requestedAudioIndex = setpoint; setMasterVolume(speed); return; }
    if (id == V_ASYMMETRY) { isAsymmetric = (setpoint > 0); return; }
    
    if (id == V_IDLE_STATE) { /* active_idle_state = setpoint; */ return; }
    if (id == V_PLAY_ANIM) { 
        active_anim_id = setpoint; 
        current_frame_idx = 0; 
        anim_start_time = millis(); 
        return; 
    }
    
    if (joint_is_active[id]) {
      engine_states[id].target_position = ROBOT_CONFIG[id].cmd_min + ((setpoint * (ROBOT_CONFIG[id].cmd_max - ROBOT_CONFIG[id].cmd_min)) / 255);
      engine_states[id].target_velocity = speed;
      if (speed == 255) {
          engine_states[id].current_position = engine_states[id].target_position;
          engine_states[id].current_velocity = 0;
          updateJointPhysics(id); 
      }
    }
}

// --- REAL-TIME KINEMATICS ENGINE ---
void updateJointPhysics(uint8_t joint_id) {
    BinJointConfig config = ROBOT_CONFIG[joint_id];
    EngineState& state = engine_states[joint_id];
    
    // FIREWALL: Prevent divide-by-zero hardware panics if config.bin is empty
    if (config.max_acc == 0) config.max_acc = 1; 

    int32_t distance_to_target = state.target_position - state.current_position;
    int32_t direction = (distance_to_target > 0) ? 1 : -1;
    int32_t abs_distance = abs(distance_to_target);

    if (abs_distance <= 2) {
        state.current_position = state.target_position;
        state.current_velocity = 0;
    } else {
        int32_t current_speed = abs(state.current_velocity);
        int32_t stopping_distance = (current_speed * current_speed) / (2 * config.max_acc);

        if (abs_distance <= stopping_distance) {
            current_speed -= config.max_acc;
            if (current_speed < config.max_acc) current_speed = config.max_acc;
        } else if (current_speed < state.target_velocity) {
            current_speed += config.max_acc;
            if (current_speed > state.target_velocity) current_speed = state.target_velocity;
            if (current_speed > config.max_spd) current_speed = config.max_spd;
        }

        state.current_velocity = current_speed * direction;
        state.current_position += state.current_velocity;

        if ((direction == 1 && state.current_position > state.target_position) ||
            (direction == -1 && state.current_position < state.target_position)) {
            state.current_position = state.target_position;
        }
    }

    if (config.control_type == 0 && config.hardware_address >= 0 && config.hardware_address < 6) { 
        if (!physical_servos[config.hardware_address].attached()) {
             physical_servos[config.hardware_address].attach(config.hardware_address);
        }
        physical_servos[config.hardware_address].writeMicroseconds(state.current_position);
    } 
    else if (config.control_type == 1 && config.hardware_address >= 0 && config.hardware_address < 16) { 
        uint16_t pulse_width_ticks = (state.current_position * 4096) / 20000;
        uint16_t on_tick = (config.hardware_address * 256) % 4096; 
        uint16_t off_tick = (on_tick + pulse_width_ticks) % 4096;
        pca9685.setPWM(config.hardware_address, on_tick, off_tick);
    }
}

// --- MAIN LOOP ---
void loop() {
  unsigned long currentMillis = millis();

  // 1. USB SERIAL PARSING 
  // Loop continually to drain the ENTIRE OS serial buffer so it never desyncs!
  while (Serial.available() > 0) {
      uint8_t header = Serial.read();
      
      if (header == 0xAA) {
          uint8_t count;
          if (Serial.readBytes(&count, 1) == 1 && count <= 16) {
              for (uint8_t i = 0; i < count; i++) {
                  uint8_t packet[3];
                  if (Serial.readBytes(packet, 3) == 3) {
                      pushCommandToEngine(packet[0], packet[1], packet[2]);
                  }
              }
          }
      }
      else if (header == 0xBB) {
          uint8_t cmd;
          if (Serial.readBytes(&cmd, 1) == 1) {
              if (cmd == 0x01) {
                  uint32_t cv = 0;
                  if (FFat.exists("/config.bin")) {
                      File f = FFat.open("/config.bin", "r");
                      if (f && f.size() >= 8) { f.seek(4); f.read((uint8_t*)&cv, 4); }
                      if (f) f.close();
                  }
                  Serial.write((uint8_t*)&cv, 4);
              }
              else if (cmd == 0x02) {
                  uint32_t fs;
                  if (Serial.readBytes((char*)&fs, 4) == 4) {
                      uploadFile = FFat.open("/config.bin", "w");
                      if (uploadFile) Serial.write(ACK_BYTE);
                  }
              }
              else if (cmd == 0x03) {
                  uint8_t cl;
                  if (Serial.readBytes(&cl, 1) == 1) {
                      uint8_t buf[64];
                      if (Serial.readBytes(buf, cl) == cl) {
                          if (uploadFile) uploadFile.write(buf, cl);
                          Serial.write(ACK_BYTE);
                      }
                  }
              }
              else if (cmd == 0x04) {
                  if (uploadFile) uploadFile.close();
                  Serial.write(ACK_BYTE);
                  loadHardwareConfig(); 
              }
          }
      }
      else if (header == 0xCC) {
          uint8_t cmd;
          if (Serial.readBytes(&cmd, 1) == 1) {
              if (cmd == 0x01) {
                  uint32_t ch = 0;
                  if (FFat.exists("/anims.bin")) {
                      File f = FFat.open("/anims.bin", "r");
                      if (f && f.size() >= 8) { f.seek(4); f.read((uint8_t*)&ch, 4); }
                      if (f) f.close();
                  }
                  Serial.write((uint8_t*)&ch, 4);
              }
              else if (cmd == 0x02) {
                  uint32_t fs;
                  if (Serial.readBytes((char*)&fs, 4) == 4) {
                      uploadFile = FFat.open("/anims.bin", "w");
                      if (uploadFile) Serial.write(ACK_BYTE);
                  }
              }
              else if (cmd == 0x03) {
                  uint8_t cl;
                  if (Serial.readBytes(&cl, 1) == 1) {
                      uint8_t buf[64];
                      if (Serial.readBytes(buf, cl) == cl) {
                          if (uploadFile) uploadFile.write(buf, cl);
                          Serial.write(ACK_BYTE);
                      }
                  }
              }
              else if (cmd == 0x04) {
                  if (uploadFile) uploadFile.close();
                  Serial.write(ACK_BYTE);
                  loadAnimations(); 
              }
          }
      }
  }

  // 2. Playback Engine
  if (active_anim_id != 0 && activeAnimations != nullptr) {
      int target_index = active_anim_id - 1;
      
      if (target_index >= 0 && target_index < activeAnimationCount) {
          BinAnimation* anim = &activeAnimations[target_index];
          uint32_t elapsed_tenths = (currentMillis - anim_start_time) / 100;

          while (current_frame_idx < anim->kf_count && anim->keyframes[current_frame_idx].time_tenths <= elapsed_tenths) {
              BinKeyframe& kf = anim->keyframes[current_frame_idx];
              for(int c = 0; c < kf.cmd_count; c++) {
                  pushCommandToEngine(kf.commands[c].joint_id, kf.commands[c].setpoint, kf.commands[c].speed);
              }
              current_frame_idx++;
          }

          if (current_frame_idx >= anim->kf_count) {
              active_anim_id = 0;
          }
      } else {
          active_anim_id = 0;
      }
  }

  // 3. Physical Kinematics Engine Pipeline (50Hz / 20ms)
  if (currentMillis - lastPhysicsTick >= 20) {
    lastPhysicsTick = currentMillis;
    for (int i = 0; i < 256; i++) {
      if (joint_is_active[i] && engine_states[i].target_velocity != 255) updateJointPhysics(i);
    }
  }

  // 4. Dual SPI Rendering Loop
  float t = currentMillis / 1000.0;
  if (currentMillis - lastFrameTime > 0) currentFPS = 1000 / (currentMillis - lastFrameTime);
  lastFrameTime = currentMillis;

  if (!isAsymmetric) {
    renderEyeFrame(t, false);
    img.setTextColor(TFT_GREEN); img.setTextDatum(TC_DATUM); img.drawString(String(currentFPS), CENTER_X, 15, 2);
    digitalWrite(TFT_CS1, LOW); digitalWrite(TFT_CS2, LOW);
    img.pushSprite(OFFSET, OFFSET);
    digitalWrite(TFT_CS1, HIGH); digitalWrite(TFT_CS2, HIGH);
  } else {
    renderEyeFrame(t, false);
    img.setTextColor(TFT_GREEN); img.setTextDatum(TC_DATUM); img.drawString(String(currentFPS), CENTER_X, 15, 2);
    digitalWrite(TFT_CS1, LOW); img.pushSprite(OFFSET, OFFSET); digitalWrite(TFT_CS1, HIGH);
    
    renderEyeFrame(t, true);
    img.setTextColor(TFT_GREEN); img.setTextDatum(TC_DATUM); img.drawString(String(currentFPS), CENTER_X, 15, 2);
    digitalWrite(TFT_CS2, LOW); img.pushSprite(OFFSET, OFFSET); digitalWrite(TFT_CS2, HIGH);
  }
}